[dependencies]

[package]
  cjc-version = "0.51.4"
  compile-option = ""
  description = "仓颉HTTP服务端框架"
  link-option = ""
  name = "server_framework"
  output-type = "executable"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
